client_id = "69a7c91d263bf9d9f71cfe63012e7ad9"
name = "Guper Loyalty Cloud"
application_url = "https://healthconnectdaily.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = [
  "https://healthconnectdaily.com/auth/callback"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
uri = "/webhooks/orders-paid"
topics = ["orders/paid"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[[webhooks.subscriptions]]
uri = "/webhooks/refunds-create"
topics = ["refunds/create"]

[[webhooks.subscriptions]]
uri = "/webhooks/customers-create"
topics = ["customers/create"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[access_scopes]
scopes = "read_customers,read_orders,write_metaobject_definitions,write_metaobjects,write_products,write_discounts,read_script_tags,write_script_tags,read_products,write_customers"

[app_proxy]
url = "https://healthconnectdaily.com"
subpath = "guper"
prefix = "apps"